### ISSUE TITLE
能支持组合api吗

### ISSUE THREAD

**Issue by aohanhe** [annnhan/doc-vue#1]
我试了一下，可以使用在defineComponent中，但是组合api方式是不行的

**Comment by annnhan** [comment]
暂时不支持

**Comment by vxhly** [comment]
我依托于本库实现了 script-setup 的代码文档生成，但是如果使用 ts 标注的代码，解析有些复杂，尚在改进中
仓库地址 #https://github.com/denaro-org/doc-vue3
@[aohanhe](https://github.com/aohanhe) @[annnhan](https://github.com/annnhan)

**Comment by annnhan** [comment]
赞 @vxhly

**Comment by annnhan** [comment]
现在支持，请升级到2.0.0

**Comment by annnhan** [comment]
现在支持啦，请升级到2.0.0
